/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 3d_voxel_dog.gltf 
Author: Takuya (https://sketchfab.com/craftzdog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-dog-7604c96da44a44ba900c51e753fb6339
Title: Voxel Dog
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3d_voxel_dog.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2.4, -2]} rotation={[-1.566, 0, 0.6]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.palette} position={[2, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[2, 0, -2]} scale={[7.05, 1, 7.05]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d_voxel_dog.gltf')
